version: '3.7'

services:
  core:
    container_name: core
    build:
      context: ./core
      target: development
    ports:
      - 3000:3000
    command: npm run start
    networks:
      - webnet
    depends_on:
      - redis
  developers:
    container_name: developers
    build:
        context: ./developers
        target: development
    ports:
        - 3002:3002
    command: npm run start
    networks:
        - webnet
    depends_on:
        - redis
  redis:
    container_name: redis
    image: redis
    ports:
        - 6379:6379
    networks:
      - webnet
networks:
  webnet: